version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
      - creds.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - creds.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  db:
  pgadmin: