version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - creds.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - creds.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

  redis:
    image: "redis:latest"
    container_name: redis

volumes:
  db:
  pgadmin: