"""Next migrations

Revision ID: c0b0d47e9f4c
Revises: 1819f2e8e4ae
Create Date: 2023-05-17 13:54:27.072628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b0d47e9f4c'
down_revision = '1819f2e8e4ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hotels', ['image_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels', type_='unique')
    # ### end Alembic commands ###
